services:
  db:
    image: postgres:17.4
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - dev.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - proyecto_final_postgres_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    env_file:
      - dev.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  proyecto_final_postgres_data:
    name: proyecto_final_postgres_data
  pgadmin_data:
    name: pgadmin_data