name: Deploy Backend to Render

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

        #TODO: FIND OUT IF THIS IS NEEDED
      # - name: Run migrations
      #   working-directory: ./backend
      #   run: npm run migrate:prod
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Trigger Render deployment
        run: curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
